import { useEffect, useState } from 'react'
import type { AppClient } from '../api/client'

export function FolderInspector({ api, path, assetFilter, assetPattern, onUseFolder, onCancel }: { api: AppClient; path: string; assetFilter: string; assetPattern: string; onUseFolder: (path: string, result: Record<string, unknown>) => void; onCancel: () => void }) {
  const [candidate, setCandidate] = useState(path)
  const [report, setReport] = useState<Record<string, unknown> | null>(null)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!candidate) return; let active = true; void api.inspectFolder({ path: candidate, asset_filter: assetFilter, asset_pattern: assetPattern }).then((value) => { if (active) { setReport(value); setError(null) } }).catch((exc) => { if (active) setError(exc instanceof Error ? exc.message : 'Folder inspection failed.') }); return () => { active = false } }, [api, candidate, assetFilter, assetPattern])
  const samples = Array.isArray(report?.sample_files) ? report.sample_files.map(String) : []
  return <section className="card folder-inspector" aria-label="Folder inspector"><div className="detail-heading"><div><h3>Inspect folder</h3><p className="muted">Candidate changes stay local until Use folder.</p></div><button className="button" onClick={onCancel}>Cancel</button></div><label className="field"><span>Candidate folder</span><input value={candidate} onChange={(event) => setCandidate(event.target.value)} /></label>{error && <div className="alert alert-danger" role="alert">{error}</div>}{report && <><div className="detail-grid"><div><span className="field-label">Matching assets</span><strong>{String(report.selected_count ?? 'Not available')}</strong></div><div><span className="field-label">Eligible records</span><strong>{String(report.eligible_records ?? 'Not available')}</strong></div><div><span className="field-label">Excluded</span><strong>{String(report.excluded_count ?? 0)}</strong></div><div><span className="field-label">Invalid</span><strong>{String(report.invalid_count ?? 0)}</strong></div><div><span className="field-label">Date range</span><strong>{String((report.date_range as Record<string, unknown> | undefined)?.start ?? 'Not available')} – {String((report.date_range as Record<string, unknown> | undefined)?.end ?? 'Not available')}</strong></div></div><h4>Sample files</h4><ul>{samples.map((item) => <li key={item}><code>{item}</code></li>)}</ul><details><summary>Exclusions</summary><pre>{JSON.stringify(report.excluded_files ?? [], null, 2)}</pre></details><button className="button primary" disabled={report.ready !== true} onClick={() => onUseFolder(candidate, report)}>{report.ready === true ? 'Use folder' : 'Folder is not ready'}</button></>}</section>
}

export default FolderInspector
